/*
 * OVERVIEW_DATA schema for plans/overview.html.
 *
 * generatedAt: ISO 8601 timestamp for the dashboard data snapshot.
 * generatedFromCommit: short git SHA that the dashboard was generated against.
 * tasks: task-row data owned by downstream task-port stories; empty in this foundation story.
 * phaseTree: phase-tree data owned by downstream phase-tree stories; empty in this foundation story.
 * lastTouched: map of taskId to ISO timestamp for the last metadata or status edit.
 * periodic: map of periodic taskId to intervalDays, lastRunId, and nextDueAt scheduling metadata.
 * cadence: map of taskId to cadence marker; currently "periodic" for recurring tasks.
 * runs: chronological history records for completed, failed, partial, deferred, or obsolete task runs.
 * effort: map of taskId to estimated effort in hours.
 * risk: map of taskId to low, medium, or high implementation risk.
 * workstream: map of taskId to dashboard workstream key.
 * sizeBucket: map of taskId to quick, small, medium, or large estimate bucket.
 * spawnedFrom: map of childTaskId to parentTaskId for research/audit follow-up lineage.
 *
 * Each downstream story mutates only its own array body (US-002/US-003 append to tasks[]; US-004 appends to phaseTree[]). The top-level object skeleton — braces, key order, comma layout — must not be re-formatted by downstream stories. This isolation lets US-003 and US-004 run in parallel worktrees without merge conflicts on the object literal.
 */
window.OVERVIEW_DATA = {
  "generatedAt": "2026-05-14T20:00:00Z",
  "generatedFromCommit": "d279d49d",
  "tasks": [],
  "phaseTree": [],
  "lastTouched": {
    "perf-WS1": "2026-05-13T22:30:00Z",
    "perf-WS3": "2026-05-13T22:00:00Z",
    "3a-skills": "2026-05-13T21:30:00Z",
    "F-013-perms": "2026-05-13T21:00:00Z",
    "F-015-toast": "2026-05-14T07:00:00Z",
    "mcp-discovery": "2026-05-13T12:39:11-07:00",
    "codex-parity-audit": "2026-05-13T23:30:00Z",
    "perf-WS2": "2026-05-13T19:30:00Z",
    "1a-fork-doc": "2026-05-13T23:30:00Z",
    "1b-multidev": "2026-05-13T19:30:00Z",
    "3b-agents": "2026-05-13T19:30:00Z",
    "3c-hooks": "2026-05-14T17:30:00Z",
    "3d-workers": "2026-05-13T19:30:00Z",
    "3fg-package": "2026-05-13T19:30:00Z",
    "3h-options": "2026-05-14T16:00:00Z",
    "userid-cleanup": "2026-05-13T21:45:00Z",
    "polish-Fs": "2026-05-13T19:30:00Z",
    "happy-upstream-sync": "2026-05-14T01:30:00Z",
    "codex-upstream-rebase": "2026-05-14T01:30:00Z",
    "agent-view-research": "2026-05-14T06:00:00Z",
    "plugin-scope-agents": "2026-05-14T03:00:00Z",
    "agent-comms": "2026-05-14T03:00:00Z",
    "channels-research": "2026-05-14T09:00:00Z",
    "async-events-design": "2026-05-14T13:30:00Z",
    "native-agent-parity": "2026-05-14T08:00:00Z",
    "roadmap-plugin": "2026-05-14T05:00:00Z",
    "agent-tree-rpc": "2026-05-14T19:00:00Z",
    "session-parent-link": "2026-05-14T15:00:00Z",
    "mobile-tree-view": "2026-05-14T06:00:00Z",
    "session-role-pill": "2026-05-14T14:00:00Z",
    "spawn-from-app": "2026-05-14T06:00:00Z",
    "agent-status-stream": "2026-05-14T19:00:00Z",
    "codex-wire-spike": "2026-05-14T18:00:00Z",
    "codex-claude-md-autoload": "2026-05-14T08:30:00Z",
    "codex-attachments": "2026-05-14T18:00:00Z",
    "codex-system-prompts": "2026-05-14T08:30:00Z",
    "codex-hooks-parity": "2026-05-14T08:30:00Z",
    "port-explorer-prompt": "2026-05-14T20:00:00Z",
    "port-plan-and-verification-roles": "2026-05-14T08:30:00Z",
    "audit-general-purpose-vs-worker": "2026-05-14T08:30:00Z",
    "3h-tail": "2026-05-14T16:30:00Z",
    "session-parent-link-writer": "2026-05-14T17:00:00Z",
    "codex-base-prompt-safety-rails": "2026-05-14T17:00:00Z",
    "codex-slash-commands": "2026-05-14T17:00:00Z",
    "codex-polish-lows": "2026-05-14T17:00:00Z",
    "codex-plan-mode-defensive": "2026-05-14T18:30:00Z",
    "codex-child-spawn-tools": "2026-05-14T19:30:00Z",
    "mcp-server-notifications": "2026-05-14T09:00:00Z",
    "codex-channels": "2026-05-14T09:00:00Z"
  },
  "periodic": {
    "happy-upstream-sync": { "intervalDays": 28, "lastRunId": "happy-upstream-sync/2026-05-03", "nextDueAt": "2026-05-31T00:00:00Z" },
    "codex-upstream-rebase": { "intervalDays": 28, "lastRunId": null, "nextDueAt": null }
  },
  "cadence": {
    "happy-upstream-sync": "periodic",
    "codex-upstream-rebase": "periodic"
  },
  "runs": [
    {
      "id": "port-explorer-prompt/2026-05-14",
      "taskId": "port-explorer-prompt",
      "ranAt": "2026-05-14T20:00:00Z",
      "outcome": "completed",
      "commits": ["e9fa64a0", "d279d49d"],
      "summary": "Filled the previously empty explorer.toml stub at codex/external/repos/codex-patched/codex-rs/core/src/agent/builtins/explorer.toml with a paraphrased Explore prompt (1538 chars, no brand strings, no 6-word verbatim spans from Claude's source — license review approved per plans/native-agent-parity.md §4 posture). Codex-side commit e9fa64a0 on feat/explorer-role-prompt: 3 files +108/-7 — explorer.toml content, role_tests.rs updated (renamed test + new invariant test + session-flags assert + SANDBOX PATCH markers), codex/docs/implementation/patch-surface.md §17 new + §14 row 21. codexu pointer-bump d279d49d (1 file, +1/-1) bumping codex submodule from 17999363 → e9fa64a0. 9 of 10 stories closed (US-006 smoke deferred to post-publish workflow — local rebuild needs LLVM/xwin/V8 env; will be covered by /publish-sandbox-patch + /verify when run). License posture verified at <job_dir>/license-review-approval.md. First piece of the native-agent-parity follow-up wave to ship — no role.rs match-arm change needed (file already wired)."
    },
    {
      "id": "codex-wire-spike/2026-05-14",
      "taskId": "codex-wire-spike",
      "ranAt": "2026-05-14T18:00:00Z",
      "outcome": "completed",
      "commits": ["06e0025b"],
      "summary": "Wire-acceptance spike against codex 0.125 resolved the three open questions blocking Gaps 2/3/5 from plans/codex-agent-parity-audit.md. Deliverables: tasks/spikes/codex-wire-spike.mjs (new, ~897-line all-in-one harness that spawns a real codex app-server and sends hand-crafted JSON-RPC requests) + plans/codex-agent-parity-audit.md 'Wire spike results' section appended with the concrete answers + Gap 2/3/5 cross-refs. Unblocks codex-attachments (Gap 3) and informs codex-claude-md-autoload (Gap 2) + future codex-slash-commands (Gap 5). Per session worktree-isolation lesson, this work landed via the .worktrees/codex-wire-spike worktree on a codex-wire-spike branch (cleanup: git worktree remove + git branch -D after the operator confirms)."
    },
    {
      "id": "session-parent-link/2026-05-14",
      "taskId": "session-parent-link",
      "ranAt": "2026-05-14T15:00:00Z",
      "outcome": "completed",
      "commits": ["11c3eafb"],
      "summary": "Shipped parentSessionId + spawnedChildren[] on Session.metadata (read path only; CLI writer wiring deferred to a separate session-parent-link-writer task). Files: packages/happy-app/sources/sync/storageTypes.ts (schema extended + .spec.ts coverage), packages/happy-cli/src/api/types.ts (CLI mirror), packages/happy-app/sources/sync/sync.ts (new normalizeMetadataParentChildRefs called from toCompositeSession + update-session ingress — drops non-string parentSessionId / non-array spawnedChildren), packages/happy-app/sources/sync/storage.ts (new getSessionParent + getSessionChildren helpers with typeof/Array.isArray backstop), packages/happy-app/CLAUDE.md (sync-invariants paragraph). Phase 5a converged in 2 rounds: 10 findings (1 High = crash path on malformed wire payloads, 8 fixed + 2 already-fixed-by-prior-commit). 1085/1085 happy-app tests pass. Unblocks mobile-tree-view + spawn-from-app per plans/agent-view-research.md §6. Deferred: CLI writer wiring (createSessionMetadata, daemon/forkSession HAPPY_FORKED_FROM_SESSION_ID, codex/runCodex, apiSession.updateMetadata) — tracked as a separate session-parent-link-writer task per the plan's Open Questions."
    },
    {
      "id": "mcp-discovery/2026-05-13",
      "taskId": "mcp-discovery",
      "ranAt": "2026-05-13T12:39:11-07:00",
      "outcome": "completed",
      "commits": ["86f35fa8", "1cf6b4e2"],
      "summary": "per-cwd .mcp.json discovery for codex agent: Zod-validated loader for project-level MCP servers (stdio + HTTP transports with command-XOR-url superRefine, type-strip after validation, passthrough for Codex-supported extras), wired into both client.startThread and client.resumeThread call sites in runCodex.ts with a single captured cwdAtStart. Reserved 'happy' bridge name is case-insensitive + trimmed. 14 helper unit tests + 4 mocked acceptance tests (start ×3 + resume ×1 without mocking ./resumeExistingThread). Closes codexu-roadmap 'Codex agent project-.mcp.json parity' bullet and Gap 1 in codex-agent-parity-audit.md."
    },
    {
      "id": "session-role-pill/2026-05-14",
      "taskId": "session-role-pill",
      "ranAt": "2026-05-14T14:00:00Z",
      "outcome": "completed",
      "commits": ["7e9f724c"],
      "summary": "Shipped flavor + model + permission-mode pills inline in the session-list row (merge 7e9f724c absorbed 5 ralph commits from branch ralph/session-role-pill: US-001 SessionRowData metadata extension, US-002 helpers + pill row on SessionItem, US-003 snapshot/structural tests, plus 2 post-review fixes incl. an Image-element assertion). Files: packages/happy-app/sources/components/SessionsList.tsx (SessionItem memo extended to render the 3 pills beneath the subtitle) + sources/sync/storage.ts (SessionRowData extended with model + permission-mode fields). No schema changes — pure UI surfacing of metadata already in Session.metadata. First piece of the agent-view-research follow-up wave to ship."
    },
    {
      "id": "audit-general-purpose-vs-worker/2026-05-14",
      "taskId": "audit-general-purpose-vs-worker",
      "ranAt": "2026-05-14T11:00:00Z",
      "outcome": "completed",
      "commits": [],
      "summary": "No-op merge finding (acceptance path b). Codex's worker role is description-only (role.rs:382-394, config_file: None) — there's no developer_instructions layer to merge Claude's safety rails into. The two real gaps (Claude's 'NEVER create files unless absolutely necessary' + 'NEVER proactively create *.md / README files') ARE missing from codex's base prompt at gpt_5_2_prompt.md:156,158 (only weak abstract analogues), but the correct fix-site is launcher-injected additional_instructions (overlay path per AGENTS.override.md tenet 1), not worker-only enforcement which would skip the main-agent flow. Recommend: land port-explorer-prompt + port-plan-and-verification-roles first; revisit base-prompt overlay separately. plans/native-agent-parity.md §2.4 updated with the finding; §6 Q6 marked resolved."
    },
    {
      "id": "1a-fork-doc/2026-05-14",
      "taskId": "1a-fork-doc",
      "ranAt": "2026-05-14T07:00:00Z",
      "outcome": "completed",
      "commits": ["7fa6ff3b"],
      "summary": "Phase 1a — Codex fork strategy committed. Locks the codex submodule fork model: gim-home/codex as the submodule, openai/codex tracked as a subtree mirror under external/repos/codex-patched/codex-rs/, divergence work in codex-rs-overlay/ as overlay crates (precedent: codex-copilot, codex-copilot-launcher, codex-invariant-tests). Submodule-pointer bumps on codexu main are separate commits after the codex-side commit lands on gim-home/codex. Doc set: codex/docs/implementation/architecture.md (Fork strategy section), codex/docs/implementation/patch-surface.md (upcoming patches catalog — Phase 2c plugin scoping, Phase 2d AskUserQuestion, Phase 7 Claude-via-Copilot), codex/CLAUDE.md (top-level pointer + minimize-conflict-surface tenet). codexu submodule pointer bumped in commit 7fa6ff3b; roadmap §Decisions made entry added."
    },
    {
      "id": "channels-research/2026-05-13",
      "taskId": "channels-research",
      "ranAt": "2026-05-14T09:00:00Z",
      "outcome": "completed",
      "commits": [],
      "summary": "Research-only deliverable: plans/channels-research.md (~570 lines). Findings: Claude Code's 'channels' is a real branded feature with three JSON-RPC methods (notifications/claude/channel, .../permission_request, .../permission), seven-gate registration, prompt-queue enqueue semantics. Codex's rmcp-client already decodes every MCP notification kind but every LoggingClientHandler is tracing-only; elicitation is the one working bidirectional precedent to copy. MCP spec 2025-11-25 does NOT standardize channels; notifications + Streamable HTTP SSE cover state-change push; no spec primitive for agent preemption (only soft-interrupt feasible). Two-stage recommendation: Stage A `mcp-server-notifications` (~3-5d, wire handler→agent bridge via overlay crate codex-mcp-bridge/ + ~12-line + ~30-line sandbox-patch seams; default-off Feature gate); Stage B `codex-channels` (~1.5-2d on top of Stage A; deferred — operator decision required on whether the channels framing is needed vs raw notifications). Phase 2d (ask_user_question) is complementary, not blocking. async-events-design unblocked by this doc."
    },
    {
      "id": "native-agent-parity/2026-05-14",
      "taskId": "native-agent-parity",
      "ranAt": "2026-05-14T08:00:00Z",
      "outcome": "completed",
      "commits": [],
      "summary": "Research-only deliverable: plans/native-agent-parity.md. Surveyed Claude Code's 6 built-in subagents; verdicts: PORT 3 (explorer — fill existing empty stub; plan — new built-in; verification — new built-in with VERDICT:PASS|FAIL|PARTIAL contract); SKIP 3 (general-purpose redundant with codex's worker; statusline-setup Claude-specific; claude-code-guide defer). Packaging: ship via include_str!() in role.rs match-arm (tolerable conflict with AGENTS.override.md tenet 1) first, plugin distribution later when manifest learns [agents.<role>]. License: paraphrase prose (research-only license on the source-mapped Claude Code checkout), keep structural patterns. Recommended 3 follow-up tasks: port-explorer-prompt (smallest), port-plan-and-verification-roles (combined PR), audit-general-purpose-vs-worker (30-min diff). 6 open questions to resolve before implementation."
    },
    {
      "id": "3h-options/2026-05-14",
      "taskId": "3h-options",
      "ranAt": "2026-05-14T16:00:00Z",
      "outcome": "completed",
      "commits": ["3bb42395", "e8284585", "2eb3f440", "a52d149b", "4eb1a9a9", "756d4290"],
      "summary": "Shipped packages/codexu-options-mode-plugin via merge of phase-3h-options-mode-plugin branch (14 commits: 6 stories + 7 review-fix + 1 docs sync; 37 files / +2251 / -136). Stories: US-001 scaffold + workspace registration; US-002 config.js port with PLUGIN_DATA-based state; US-003 session-start.js + user-prompt-submit.js port; US-004 stop.js rewrite for codex last_assistant_message + transcript scan; US-005 hooks.json + .codex-plugin/plugin.json wiring; US-006 SKILL.md discoverability + README + CLAUDE.md + statusline + roadmap closure. Phase 5a code review: 11 findings fixed in 1 round (4 High in stop.js: fail-open empty message, fail-open missing transcript, false 'hook auto-responds' claim, silenced PLUGIN_DATA-required throws + 7 Low/Medium). Phase 5b docs: 5 findings fixed. Phase 5c security: 0 findings. 37/37 plugin tests pass. 7 load-bearing invariants verified. Deferred to Phase 3h-tail: (a) codex TUI statusline plugin slot (no plugin slot exists in status_line_setup.rs), (b) codex request_user_input handler pre_tool_use_payload() override for auto-mode AskUserQuestion inter-mode."
    },
    {
      "id": "codex-parity-audit/2026-05-13",
      "taskId": "codex-parity-audit",
      "ranAt": "2026-05-13T23:30:00Z",
      "outcome": "completed",
      "commits": [],
      "summary": "Research-only deliverable: plans/codex-agent-parity-audit.md. 12 gaps catalogued with file:line evidence (3 High: project-.mcp.json discovery, project-CLAUDE.md auto-load, image-attachments-never-reach-codex; 4 Medium: hooks parity, slash commands, plan mode, custom system prompts; 5 Low: tool gating, codex-args passthrough, .claude/skills/ category mismatch, statusline, init-metadata mirror). All proposed fix-sites are happy-cli-side except Gap 6 (plan mode) which has a v2 overlay-crate option deferred — NO upstream-canonical codex edits proposed. Recommended landing order: Gap 1 mcp-discovery (already tracked), Gap 2 codex-claude-md-autoload, Gap 3 codex-attachments, Gap 7 codex-system-prompts, then Gap 4 codex-hooks-parity. One pre-flight wire-acceptance spike (30 min) covers Gaps 2/3/5."
    },
    {
      "id": "perf-WS1/2026-05-13",
      "taskId": "perf-WS1",
      "ranAt": "2026-05-13T22:00:00Z",
      "outcome": "closed-obsolete",
      "commits": ["188cfd9c", "5dae2a65", "33ec9f75"],
      "summary": "Closed as obsolete-by-design — the entire refreshTunnelClaim layer was removed end-to-end via the remove-tunnel-claim-layer merge, so the WS1 skip-when-cached optimization no longer has a roundtrip to skip."
    },
    {
      "id": "perf-WS3/2026-05-13",
      "taskId": "perf-WS3",
      "ranAt": "2026-05-13T15:56:26Z",
      "outcome": "completed",
      "commits": ["197b0148"],
      "summary": "Shipped server-side per-user event replay buffer + client lastSeenSeq handshake. Per plans/realtime-sync-perf.md §WS3."
    },
    {
      "id": "F-013-perms/2026-05-13",
      "taskId": "F-013-perms",
      "ranAt": "2026-05-13T21:00:00Z",
      "outcome": "closed-obsolete",
      "commits": ["bfe7ef67"],
      "summary": "Closed as obsolete-by-design — Phase 5 drop-Claude supersedes. Latent path left at packages/happy-cli/src/claude/utils/permissionHandler.ts:87-89."
    },
    {
      "id": "happy-upstream-sync/2026-05-03",
      "taskId": "happy-upstream-sync",
      "ranAt": "2026-05-03T00:00:00Z",
      "outcome": "completed",
      "commits": ["25fe2cf3"],
      "summary": "Absorbed 79 upstream slopus/happy commits / 1971 files / 25 conflicts. Headline: codium plugin system, theme system, Codex OAuth via PKCE, Streamdown rendering, model adds (Opus 4.7, GPT 5.5)."
    },
    {
      "id": "agent-view-research/2026-05-14",
      "taskId": "agent-view-research",
      "ranAt": "2026-05-14T06:00:00Z",
      "outcome": "completed",
      "commits": [],
      "summary": "Research-only deliverable: plans/agent-view-research.md. Surveyed Claude Code's teammate-view feature (D:/harness-efforts/claude-code/worktrees/main/), codex's existing multi_agents_v2/spawn.rs primitives (READ-ONLY), and happy-app's session-list surface. Decomposed into 6 follow-up tasks tagged spawnedFrom=agent-view-research: agent-tree-rpc, session-parent-link, mobile-tree-view, session-role-pill, spawn-from-app, agent-status-stream. Effort by bucket — (a) codex runtime: 8h; (b) mobile UI: 19h; (c) both: 18h. These follow-ups ARE the Phase 6 'Long-lived teammates' implementation."
    },
    {
      "id": "agent-tree-rpc/2026-05-13",
      "taskId": "agent-tree-rpc",
      "ranAt": "2026-05-13T20:29:11Z",
      "outcome": "completed",
      "commits": ["4f5762f9", "6f327e9c", "e1a19de8", "f37c9542", "b2826f89"],
      "summary": "Shipped agent-tree RPC plumbing on branch agent-tree-rpc: shared wire schemas, happy-cli reducer and sessionGetAgentTree RPC, live agent-tree-update delta emission, Codex v2/legacy spawn-event parsing, and happy-server validation plus session/user-scoped fan-out. Real-Codex nested child acceptance remains blocked by child-agent tool availability."
    }
  ],
  "effort": {
    "perf-WS1": 0.75,
    "perf-WS3": 3,
    "3a-skills": 12,
    "F-013-perms": 0,
    "F-015-toast": 0.75,
    "mcp-discovery": 0.75,
    "codex-parity-audit": 2,
    "perf-WS2": 1.5,
    "1a-fork-doc": 2,
    "1b-multidev": 8,
    "3b-agents": 12,
    "3c-hooks": 4,
    "3d-workers": 12,
    "3fg-package": 8,
    "3h-options": 16,
    "userid-cleanup": 6,
    "polish-Fs": 8,
    "happy-upstream-sync": 6,
    "codex-upstream-rebase": 8,
    "agent-view-research": 4,
    "plugin-scope-agents": 12,
    "agent-comms": 16,
    "channels-research": 4,
    "async-events-design": 6,
    "native-agent-parity": 4,
    "roadmap-plugin": 12,
    "agent-tree-rpc": 8,
    "session-parent-link": 4,
    "mobile-tree-view": 12,
    "session-role-pill": 3,
    "spawn-from-app": 8,
    "agent-status-stream": 10,
    "codex-wire-spike": 0.5,
    "codex-claude-md-autoload": 0.75,
    "codex-attachments": 3,
    "codex-system-prompts": 2,
    "codex-hooks-parity": 8,
    "port-explorer-prompt": 3,
    "port-plan-and-verification-roles": 6,
    "audit-general-purpose-vs-worker": 0.5,
    "3h-tail": 8,
    "session-parent-link-writer": 4,
    "codex-base-prompt-safety-rails": 4,
    "codex-slash-commands": 3,
    "codex-polish-lows": 5,
    "codex-plan-mode-defensive": 2,
    "codex-child-spawn-tools": 3,
    "mcp-server-notifications": 32,
    "codex-channels": 14
  },
  "risk": {
    "perf-WS1": "low",
    "perf-WS3": "medium",
    "3a-skills": "medium",
    "F-013-perms": "low",
    "F-015-toast": "low",
    "mcp-discovery": "low",
    "codex-parity-audit": "low",
    "perf-WS2": "medium",
    "1a-fork-doc": "low",
    "1b-multidev": "medium",
    "3b-agents": "medium",
    "3c-hooks": "low",
    "3d-workers": "medium",
    "3fg-package": "low",
    "3h-options": "medium",
    "userid-cleanup": "medium",
    "polish-Fs": "medium",
    "happy-upstream-sync": "medium",
    "codex-upstream-rebase": "medium",
    "agent-view-research": "low",
    "plugin-scope-agents": "medium",
    "agent-comms": "high",
    "channels-research": "low",
    "async-events-design": "low",
    "native-agent-parity": "low",
    "roadmap-plugin": "medium",
    "agent-tree-rpc": "medium",
    "session-parent-link": "medium",
    "mobile-tree-view": "medium",
    "session-role-pill": "low",
    "spawn-from-app": "medium",
    "agent-status-stream": "high",
    "codex-wire-spike": "low",
    "codex-claude-md-autoload": "low",
    "codex-attachments": "medium",
    "codex-system-prompts": "low",
    "codex-hooks-parity": "medium",
    "port-explorer-prompt": "low",
    "port-plan-and-verification-roles": "medium",
    "audit-general-purpose-vs-worker": "low",
    "3h-tail": "medium",
    "session-parent-link-writer": "medium",
    "codex-base-prompt-safety-rails": "medium",
    "codex-slash-commands": "medium",
    "codex-polish-lows": "low",
    "codex-plan-mode-defensive": "low",
    "codex-child-spawn-tools": "low",
    "mcp-server-notifications": "medium",
    "codex-channels": "medium"
  },
  "workstream": {
    "perf-WS1": "perf",
    "perf-WS3": "perf",
    "perf-WS2": "perf",
    "3a-skills": "codex-spec",
    "1a-fork-doc": "codex-spec",
    "1b-multidev": "codex-spec",
    "3b-agents": "codex-spec",
    "3c-hooks": "codex-spec",
    "3d-workers": "codex-spec",
    "3fg-package": "codex-spec",
    "3h-options": "codex-spec",
    "mcp-discovery": "codex-parity",
    "codex-parity-audit": "codex-parity",
    "F-013-perms": "polish",
    "F-015-toast": "polish",
    "polish-Fs": "polish",
    "userid-cleanup": "cleanup",
    "happy-upstream-sync": "upstream",
    "codex-upstream-rebase": "upstream",
    "agent-view-research": "agent-arch",
    "plugin-scope-agents": "agent-arch",
    "agent-comms": "agent-arch",
    "channels-research": "agent-arch",
    "async-events-design": "agent-arch",
    "native-agent-parity": "agent-arch",
    "roadmap-plugin": "tooling",
    "agent-tree-rpc": "agent-arch",
    "session-parent-link": "agent-arch",
    "mobile-tree-view": "agent-arch",
    "session-role-pill": "agent-arch",
    "spawn-from-app": "agent-arch",
    "agent-status-stream": "agent-arch",
    "codex-wire-spike": "codex-parity",
    "codex-claude-md-autoload": "codex-parity",
    "codex-attachments": "codex-parity",
    "codex-system-prompts": "codex-parity",
    "codex-hooks-parity": "codex-parity",
    "port-explorer-prompt": "agent-arch",
    "port-plan-and-verification-roles": "agent-arch",
    "audit-general-purpose-vs-worker": "agent-arch",
    "3h-tail": "codex-spec",
    "session-parent-link-writer": "agent-arch",
    "codex-base-prompt-safety-rails": "agent-arch",
    "codex-slash-commands": "codex-parity",
    "codex-polish-lows": "codex-parity",
    "codex-plan-mode-defensive": "codex-parity",
    "codex-child-spawn-tools": "agent-arch",
    "mcp-server-notifications": "agent-arch",
    "codex-channels": "agent-arch"
  },
  "sizeBucket": {
    "perf-WS1": "quick",
    "perf-WS3": "small",
    "3a-skills": "large",
    "F-013-perms": "quick",
    "F-015-toast": "quick",
    "mcp-discovery": "quick",
    "codex-parity-audit": "small",
    "perf-WS2": "small",
    "1a-fork-doc": "small",
    "1b-multidev": "medium",
    "3b-agents": "large",
    "3c-hooks": "small",
    "3d-workers": "large",
    "3fg-package": "medium",
    "3h-options": "large",
    "userid-cleanup": "medium",
    "polish-Fs": "medium",
    "happy-upstream-sync": "medium",
    "codex-upstream-rebase": "medium",
    "agent-view-research": "small",
    "plugin-scope-agents": "large",
    "agent-comms": "large",
    "channels-research": "small",
    "async-events-design": "medium",
    "native-agent-parity": "small",
    "roadmap-plugin": "large",
    "agent-tree-rpc": "medium",
    "session-parent-link": "small",
    "mobile-tree-view": "large",
    "session-role-pill": "small",
    "spawn-from-app": "medium",
    "agent-status-stream": "large",
    "codex-wire-spike": "quick",
    "codex-claude-md-autoload": "quick",
    "codex-attachments": "small",
    "codex-system-prompts": "small",
    "codex-hooks-parity": "medium",
    "port-explorer-prompt": "small",
    "port-plan-and-verification-roles": "medium",
    "audit-general-purpose-vs-worker": "quick",
    "3h-tail": "medium",
    "session-parent-link-writer": "small",
    "codex-base-prompt-safety-rails": "small",
    "codex-slash-commands": "small",
    "codex-polish-lows": "small",
    "codex-plan-mode-defensive": "small",
    "codex-child-spawn-tools": "small",
    "mcp-server-notifications": "large",
    "codex-channels": "medium"
  },
  "spawnedFrom": {
    "_comment": "Map of childTaskId -> parentTaskId. Populated when a research task or audit task lands and surfaces new follow-up tasks.",
    "agent-tree-rpc": "agent-view-research",
    "session-parent-link": "agent-view-research",
    "mobile-tree-view": "agent-view-research",
    "session-role-pill": "agent-view-research",
    "spawn-from-app": "agent-view-research",
    "agent-status-stream": "agent-view-research",
    "codex-wire-spike": "codex-parity-audit",
    "codex-claude-md-autoload": "codex-parity-audit",
    "codex-attachments": "codex-parity-audit",
    "codex-system-prompts": "codex-parity-audit",
    "codex-hooks-parity": "codex-parity-audit",
    "port-explorer-prompt": "native-agent-parity",
    "port-plan-and-verification-roles": "native-agent-parity",
    "audit-general-purpose-vs-worker": "native-agent-parity",
    "3h-tail": "3h-options",
    "session-parent-link-writer": "session-parent-link",
    "codex-base-prompt-safety-rails": "audit-general-purpose-vs-worker",
    "codex-slash-commands": "codex-parity-audit",
    "codex-polish-lows": "codex-parity-audit",
    "codex-plan-mode-defensive": "codex-parity-audit",
    "codex-child-spawn-tools": "agent-tree-rpc",
    "mcp-server-notifications": "channels-research",
    "codex-channels": "channels-research"
  }
};
