import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'

import { afterEach, describe, expect, test } from 'vitest'

import { parseSpawnLauncher } from './parse-spawn-launcher.mjs'

const fixtureRoots = []

afterEach(() => {
    for (const fixtureRoot of fixtureRoots.splice(0)) {
        fs.rmSync(fixtureRoot, { recursive: true, force: true })
    }
})

describe('parseSpawnLauncher', () => {
    test('parses a real-format launcher', () => {
        const result = parseSpawnLauncher('D:/harness-efforts/codexu/.crews/spawn-launchers/alice-1778830606020.ps1')

        expect(result).toEqual({
            initialPrompt: 'Say hello in one sentence.',
            memberName: 'alice',
            crewName: 'smoke',
        })
    })

    test('handles PowerShell single-quote escaping and returns the final quoted claude argument', () => {
        const launcherPath = writeLauncher(
            'quoted-worker-1778830606020.ps1',
            `# Auto-generated by crews plugin (spawnMember).
# name: quoted-worker   crew: quote-crew
$env:CREWS_ROLE = 'member'
$env:CREWS_NAME = 'quoted-worker'
$env:CREWS_CREW = 'quote-crew'
claude --name 'quoted-worker' --plugin-dir 'C:\\Plugins\\crews' 'Don''t stop on TASK-123.'
$afterCommand = 'not the prompt'
`,
        )

        expect(parseSpawnLauncher(launcherPath)).toEqual({
            initialPrompt: "Don't stop on TASK-123.",
            memberName: 'quoted-worker',
            crewName: 'quote-crew',
        })
    })

    test('returns null initialPrompt when the claude line is missing', () => {
        const launcherPath = writeLauncher(
            'fallback-name-1778830606020.ps1',
            `# Auto-generated by crews plugin (spawnMember).
$env:CREWS_CREW = 'quiet-crew'
`,
        )

        expect(parseSpawnLauncher(launcherPath)).toEqual({
            initialPrompt: null,
            memberName: 'fallback-name',
            crewName: 'quiet-crew',
        })
    })

    test('falls back to filename memberName for an empty file', () => {
        const launcherPath = writeLauncher('empty-1778830606020.ps1', '')

        expect(parseSpawnLauncher(launcherPath)).toEqual({
            initialPrompt: null,
            memberName: 'empty',
            crewName: null,
        })
    })
})

function writeLauncher(filename, contents) {
    const fixtureRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'parse-spawn-launcher-'))
    fixtureRoots.push(fixtureRoot)
    const launcherPath = path.join(fixtureRoot, filename)
    fs.writeFileSync(launcherPath, contents)
    return launcherPath
}
